social_media/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('regester/', views.RegesterView.as_view(), name='user_regester'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name='user_profile'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='user_unfollow')
    
]

social_media/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeClass.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>', views.PostDetailView.as_view(), name = 'post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.UserUpdateView.as_view(), name='post_update'),
    path('post/create/', views.UserCreateView.as_view(), name='post_create'),
]

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

social_media/templates/inc/messeges.html
{% if messesges %}
    {% for msg in messeges %}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

social_media/templates/inc/navbar.html
<nav class="navbar bg-body-tertiary">
    <div class="container-fluid navbar-dark bg-dark">
      <a class="navbar-brand" active href="{% url "home:home" %}">Home</a>
      {% if request.user.is_authenticated %}
      <a class="navbar-brand" active href="{% url 'account:user_profile' request.user.id %}">Profile</a>
      <a class="navbar-brand" active href="{% url 'account:user_logout' %}">Logout</a>
      {% else %}
      <a class="navbar-brand" active href="{% url 'account:user_regester' %}">Regester</a>
      <a class="navbar-brand" active href="{% url 'account:user_login' %}">Login</a>
      {% endif %}
    </div>
  </nav>